[phases.setup]
aptPkgs = ["fontconfig", "fonts-dejavu-core", "fonts-dejavu-extra"]

[phases.build]
cmds = ["fc-cache -f -v"]

[variables]
FONTCONFIG_PATH = "/etc/fonts"
FONTCONFIG_FILE = "/etc/fonts/fonts.conf"